name: Build spine-godot (All Godot 4.x versions)

env:
  SCRIPT_AES256_ENCRYPTION_KEY: "dcd1159ca7df5fae042b8f996c4f8436d1afaac5a706d9067f70db69ac697da3"

on:
  push:
    paths:
      - ".github/workflows/spine-godot.yml"
      - 'spine-godot/**'
      - 'spine-cpp/**'
  workflow_dispatch:

jobs:
  build-versions:
    strategy:
      matrix:
        version:
          [
            {"tag": "4.3-stable", "version": "4.3.stable", "mono": false},
            {"tag": "4.3-stable", "version": "4.3.stable", "mono": true},
            {"tag": "4.2.2-stable", "version": "4.2.2.stable", "mono": false},
            {"tag": "4.2.2-stable", "version": "4.2.2.stable", "mono": true},
          ]
    uses: ./.github/workflows/spine-godot-v4.yml
    with:
      godot_tag: ${{ matrix.version.tag }}
      godot_version: ${{ matrix.version.version }}
      godot_mono: ${{ matrix.version.mono }}
    secrets: inherit
